apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-powervs-1
  name: worker-1
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: worker-1-config
      namespace: default
  clusterName: ibm-powervs-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMPowerVSMachine
    name: worker-1
    namespace: default
  version: v1.19.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMPowerVSMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-powervs-1
  name: worker-1
spec:
  name: worker-1
  cloudInstanceID: "7845d372-d4e1-46b8-91fc-41051c984601"
  sshKey: mkumatag-pub-key
  image: "71a00ad7-58e6-4903-90f3-82437bc1f145"
  machineType: s922
  processor: shared
  cores: "0.25"
  memory: "8"
  network: "0ad342f5-f461-414a-a870-e2f2a2b7fa0c"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-powervs-1
  name: worker-1-config
  namespace: default
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: external
        provider-id: ibmpowervs://ibm-powervs-1/'{{ v1.local_hostname }}'
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
