// +build !ignore_autogenerated_core_v1alpha3

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1alpha4 "github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/api/v1alpha4"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1alpha4.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(a.(*APIEndpoint), b.(*v1alpha4.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*v1alpha4.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCCluster)(nil), (*v1alpha4.IBMVPCCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCCluster_To_v1alpha4_IBMVPCCluster(a.(*IBMVPCCluster), b.(*v1alpha4.IBMVPCCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCCluster)(nil), (*IBMVPCCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(a.(*v1alpha4.IBMVPCCluster), b.(*IBMVPCCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterList)(nil), (*v1alpha4.IBMVPCClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterList_To_v1alpha4_IBMVPCClusterList(a.(*IBMVPCClusterList), b.(*v1alpha4.IBMVPCClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCClusterList)(nil), (*IBMVPCClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(a.(*v1alpha4.IBMVPCClusterList), b.(*IBMVPCClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterSpec)(nil), (*v1alpha4.IBMVPCClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec(a.(*IBMVPCClusterSpec), b.(*v1alpha4.IBMVPCClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCClusterSpec)(nil), (*IBMVPCClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(a.(*v1alpha4.IBMVPCClusterSpec), b.(*IBMVPCClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterStatus)(nil), (*v1alpha4.IBMVPCClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus(a.(*IBMVPCClusterStatus), b.(*v1alpha4.IBMVPCClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCClusterStatus)(nil), (*IBMVPCClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(a.(*v1alpha4.IBMVPCClusterStatus), b.(*IBMVPCClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachine)(nil), (*v1alpha4.IBMVPCMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachine_To_v1alpha4_IBMVPCMachine(a.(*IBMVPCMachine), b.(*v1alpha4.IBMVPCMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachine)(nil), (*IBMVPCMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(a.(*v1alpha4.IBMVPCMachine), b.(*IBMVPCMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineList)(nil), (*v1alpha4.IBMVPCMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineList_To_v1alpha4_IBMVPCMachineList(a.(*IBMVPCMachineList), b.(*v1alpha4.IBMVPCMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineList)(nil), (*IBMVPCMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(a.(*v1alpha4.IBMVPCMachineList), b.(*IBMVPCMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineSpec)(nil), (*v1alpha4.IBMVPCMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(a.(*IBMVPCMachineSpec), b.(*v1alpha4.IBMVPCMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineSpec)(nil), (*IBMVPCMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(a.(*v1alpha4.IBMVPCMachineSpec), b.(*IBMVPCMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineStatus)(nil), (*v1alpha4.IBMVPCMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus(a.(*IBMVPCMachineStatus), b.(*v1alpha4.IBMVPCMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineStatus)(nil), (*IBMVPCMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(a.(*v1alpha4.IBMVPCMachineStatus), b.(*IBMVPCMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplate)(nil), (*v1alpha4.IBMVPCMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplate_To_v1alpha4_IBMVPCMachineTemplate(a.(*IBMVPCMachineTemplate), b.(*v1alpha4.IBMVPCMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineTemplate)(nil), (*IBMVPCMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(a.(*v1alpha4.IBMVPCMachineTemplate), b.(*IBMVPCMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateList)(nil), (*v1alpha4.IBMVPCMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1alpha4_IBMVPCMachineTemplateList(a.(*IBMVPCMachineTemplateList), b.(*v1alpha4.IBMVPCMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineTemplateList)(nil), (*IBMVPCMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(a.(*v1alpha4.IBMVPCMachineTemplateList), b.(*IBMVPCMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateResource)(nil), (*v1alpha4.IBMVPCMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource(a.(*IBMVPCMachineTemplateResource), b.(*v1alpha4.IBMVPCMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineTemplateResource)(nil), (*IBMVPCMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(a.(*v1alpha4.IBMVPCMachineTemplateResource), b.(*IBMVPCMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateSpec)(nil), (*v1alpha4.IBMVPCMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec(a.(*IBMVPCMachineTemplateSpec), b.(*v1alpha4.IBMVPCMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.IBMVPCMachineTemplateSpec)(nil), (*IBMVPCMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(a.(*v1alpha4.IBMVPCMachineTemplateSpec), b.(*IBMVPCMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkInterface)(nil), (*v1alpha4.NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface(a.(*NetworkInterface), b.(*v1alpha4.NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.NetworkInterface)(nil), (*NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface(a.(*v1alpha4.NetworkInterface), b.(*NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*v1alpha4.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Subnet_To_v1alpha4_Subnet(a.(*Subnet), b.(*v1alpha4.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Subnet_To_v1alpha3_Subnet(a.(*v1alpha4.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*v1alpha4.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VPC_To_v1alpha4_VPC(a.(*VPC), b.(*v1alpha4.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VPC_To_v1alpha3_VPC(a.(*v1alpha4.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(in *APIEndpoint, out *v1alpha4.APIEndpoint, s conversion.Scope) error {
	out.Address = (*string)(unsafe.Pointer(in.Address))
	out.FIPID = (*string)(unsafe.Pointer(in.FIPID))
	return nil
}

// Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(in *APIEndpoint, out *v1alpha4.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(in *v1alpha4.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Address = (*string)(unsafe.Pointer(in.Address))
	out.FIPID = (*string)(unsafe.Pointer(in.FIPID))
	return nil
}

// Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(in *v1alpha4.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCCluster_To_v1alpha4_IBMVPCCluster(in *IBMVPCCluster, out *v1alpha4.IBMVPCCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCCluster_To_v1alpha4_IBMVPCCluster is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCCluster_To_v1alpha4_IBMVPCCluster(in *IBMVPCCluster, out *v1alpha4.IBMVPCCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCCluster_To_v1alpha4_IBMVPCCluster(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in *v1alpha4.IBMVPCCluster, out *IBMVPCCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCCluster_To_v1alpha3_IBMVPCCluster is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in *v1alpha4.IBMVPCCluster, out *IBMVPCCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterList_To_v1alpha4_IBMVPCClusterList(in *IBMVPCClusterList, out *v1alpha4.IBMVPCClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.IBMVPCCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_IBMVPCClusterList_To_v1alpha4_IBMVPCClusterList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterList_To_v1alpha4_IBMVPCClusterList(in *IBMVPCClusterList, out *v1alpha4.IBMVPCClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterList_To_v1alpha4_IBMVPCClusterList(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in *v1alpha4.IBMVPCClusterList, out *IBMVPCClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IBMVPCCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in *v1alpha4.IBMVPCClusterList, out *IBMVPCClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec(in *IBMVPCClusterSpec, out *v1alpha4.IBMVPCClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ResourceGroup = in.ResourceGroup
	out.VPC = in.VPC
	out.Zone = in.Zone
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	return nil
}

// Convert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec(in *IBMVPCClusterSpec, out *v1alpha4.IBMVPCClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterSpec_To_v1alpha4_IBMVPCClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in *v1alpha4.IBMVPCClusterSpec, out *IBMVPCClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ResourceGroup = in.ResourceGroup
	out.VPC = in.VPC
	out.Zone = in.Zone
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	return nil
}

// Convert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in *v1alpha4.IBMVPCClusterSpec, out *IBMVPCClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus(in *IBMVPCClusterStatus, out *v1alpha4.IBMVPCClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha3_VPC_To_v1alpha4_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	if err := Convert_v1alpha3_Subnet_To_v1alpha4_Subnet(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(&in.APIEndpoint, &out.APIEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus(in *IBMVPCClusterStatus, out *v1alpha4.IBMVPCClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterStatus_To_v1alpha4_IBMVPCClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in *v1alpha4.IBMVPCClusterStatus, out *IBMVPCClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha4_VPC_To_v1alpha3_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	if err := Convert_v1alpha4_Subnet_To_v1alpha3_Subnet(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(&in.APIEndpoint, &out.APIEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in *v1alpha4.IBMVPCClusterStatus, out *IBMVPCClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachine_To_v1alpha4_IBMVPCMachine(in *IBMVPCMachine, out *v1alpha4.IBMVPCMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachine_To_v1alpha4_IBMVPCMachine is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachine_To_v1alpha4_IBMVPCMachine(in *IBMVPCMachine, out *v1alpha4.IBMVPCMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachine_To_v1alpha4_IBMVPCMachine(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in *v1alpha4.IBMVPCMachine, out *IBMVPCMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCMachine_To_v1alpha3_IBMVPCMachine is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in *v1alpha4.IBMVPCMachine, out *IBMVPCMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineList_To_v1alpha4_IBMVPCMachineList(in *IBMVPCMachineList, out *v1alpha4.IBMVPCMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.IBMVPCMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineList_To_v1alpha4_IBMVPCMachineList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineList_To_v1alpha4_IBMVPCMachineList(in *IBMVPCMachineList, out *v1alpha4.IBMVPCMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineList_To_v1alpha4_IBMVPCMachineList(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in *v1alpha4.IBMVPCMachineList, out *IBMVPCMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IBMVPCMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in *v1alpha4.IBMVPCMachineList, out *IBMVPCMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(in *IBMVPCMachineSpec, out *v1alpha4.IBMVPCMachineSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Zone = in.Zone
	out.Profile = in.Profile
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface(&in.PrimaryNetworkInterface, &out.PrimaryNetworkInterface, s); err != nil {
		return err
	}
	out.SSHKeys = *(*[]*string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(in *IBMVPCMachineSpec, out *v1alpha4.IBMVPCMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in *v1alpha4.IBMVPCMachineSpec, out *IBMVPCMachineSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Zone = in.Zone
	out.Profile = in.Profile
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface(&in.PrimaryNetworkInterface, &out.PrimaryNetworkInterface, s); err != nil {
		return err
	}
	out.SSHKeys = *(*[]*string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in *v1alpha4.IBMVPCMachineSpec, out *IBMVPCMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus(in *IBMVPCMachineStatus, out *v1alpha4.IBMVPCMachineStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = in.InstanceStatus
	return nil
}

// Convert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus(in *IBMVPCMachineStatus, out *v1alpha4.IBMVPCMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineStatus_To_v1alpha4_IBMVPCMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in *v1alpha4.IBMVPCMachineStatus, out *IBMVPCMachineStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = in.InstanceStatus
	return nil
}

// Convert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in *v1alpha4.IBMVPCMachineStatus, out *IBMVPCMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplate_To_v1alpha4_IBMVPCMachineTemplate(in *IBMVPCMachineTemplate, out *v1alpha4.IBMVPCMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplate_To_v1alpha4_IBMVPCMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplate_To_v1alpha4_IBMVPCMachineTemplate(in *IBMVPCMachineTemplate, out *v1alpha4.IBMVPCMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplate_To_v1alpha4_IBMVPCMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in *v1alpha4.IBMVPCMachineTemplate, out *IBMVPCMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in *v1alpha4.IBMVPCMachineTemplate, out *IBMVPCMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateList_To_v1alpha4_IBMVPCMachineTemplateList(in *IBMVPCMachineTemplateList, out *v1alpha4.IBMVPCMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.IBMVPCMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1alpha4_IBMVPCMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1alpha4_IBMVPCMachineTemplateList(in *IBMVPCMachineTemplateList, out *v1alpha4.IBMVPCMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateList_To_v1alpha4_IBMVPCMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in *v1alpha4.IBMVPCMachineTemplateList, out *IBMVPCMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IBMVPCMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in *v1alpha4.IBMVPCMachineTemplateList, out *IBMVPCMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource(in *IBMVPCMachineTemplateResource, out *v1alpha4.IBMVPCMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_IBMVPCMachineSpec_To_v1alpha4_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource(in *IBMVPCMachineTemplateResource, out *v1alpha4.IBMVPCMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in *v1alpha4.IBMVPCMachineTemplateResource, out *IBMVPCMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in *v1alpha4.IBMVPCMachineTemplateResource, out *IBMVPCMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec(in *IBMVPCMachineTemplateSpec, out *v1alpha4.IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1alpha4_IBMVPCMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec(in *IBMVPCMachineTemplateSpec, out *v1alpha4.IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1alpha4_IBMVPCMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in *v1alpha4.IBMVPCMachineTemplateSpec, out *IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in *v1alpha4.IBMVPCMachineTemplateSpec, out *IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface(in *NetworkInterface, out *v1alpha4.NetworkInterface, s conversion.Scope) error {
	out.Subnet = in.Subnet
	return nil
}

// Convert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface is an autogenerated conversion function.
func Convert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface(in *NetworkInterface, out *v1alpha4.NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkInterface_To_v1alpha4_NetworkInterface(in, out, s)
}

func autoConvert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface(in *v1alpha4.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	out.Subnet = in.Subnet
	return nil
}

// Convert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface is an autogenerated conversion function.
func Convert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface(in *v1alpha4.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkInterface_To_v1alpha3_NetworkInterface(in, out, s)
}

func autoConvert_v1alpha3_Subnet_To_v1alpha4_Subnet(in *Subnet, out *v1alpha4.Subnet, s conversion.Scope) error {
	out.Ipv4CidrBlock = (*string)(unsafe.Pointer(in.Ipv4CidrBlock))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1alpha3_Subnet_To_v1alpha4_Subnet is an autogenerated conversion function.
func Convert_v1alpha3_Subnet_To_v1alpha4_Subnet(in *Subnet, out *v1alpha4.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha3_Subnet_To_v1alpha4_Subnet(in, out, s)
}

func autoConvert_v1alpha4_Subnet_To_v1alpha3_Subnet(in *v1alpha4.Subnet, out *Subnet, s conversion.Scope) error {
	out.Ipv4CidrBlock = (*string)(unsafe.Pointer(in.Ipv4CidrBlock))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1alpha4_Subnet_To_v1alpha3_Subnet is an autogenerated conversion function.
func Convert_v1alpha4_Subnet_To_v1alpha3_Subnet(in *v1alpha4.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha4_Subnet_To_v1alpha3_Subnet(in, out, s)
}

func autoConvert_v1alpha3_VPC_To_v1alpha4_VPC(in *VPC, out *v1alpha4.VPC, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha3_VPC_To_v1alpha4_VPC is an autogenerated conversion function.
func Convert_v1alpha3_VPC_To_v1alpha4_VPC(in *VPC, out *v1alpha4.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha3_VPC_To_v1alpha4_VPC(in, out, s)
}

func autoConvert_v1alpha4_VPC_To_v1alpha3_VPC(in *v1alpha4.VPC, out *VPC, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha4_VPC_To_v1alpha3_VPC is an autogenerated conversion function.
func Convert_v1alpha4_VPC_To_v1alpha3_VPC(in *v1alpha4.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_v1alpha4_VPC_To_v1alpha3_VPC(in, out, s)
}
